apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: dukeguessr-multiplayer-server
        name: server
        imagePullPolicy: Never
        ports:
        - containerPort: 7776
          name: server
        env:
        - name: MONGO_URL
          value: mongodb://db
        - name: REDIS_URL
          value: redis://redis
        - name: UI_PORT
          value: "31775"
        - name: SERVER_PORT
          value: "7776"
        - name: HOST
          value: "localhost"
