apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  type: NodePort
  ports:
  - name: "server-service"
    port: 5776
    targetPort: 7776
    nodePort: 31776
  selector:
    app: server
